### ISSUE TITLE
Map Tile

### ISSUE THREAD

**Issue by jakeb-cloud** [ionixjunior/ionic-offline-maps#1]
How did you download the map tile inside your "MapQuest" folder?

**Comment by ionixjunior** [comment]
Hi @jakeb-cloud,
In this sample project I downloaded manually the map tiles and add the images inside project. Map tiles folder is inside www.

This tutorial shows how to implement this step by step http://www.ionixjunior.com.br/aplicativo-com-mapa-offline-usando-ionic-framework/

Is possible download map tiles at runtime, but need more implementations.
